### check healthz 
GET https://vozfc.io.vn/test/healthz

### init user
POST https://vozfc.io.vn/test/user/init

### authenticate
POST https://vozfc.io.vn/test/user/authenticate
Content-Type: application/json

{"email":"an.lethanh3@gmail.com","password":"12345678"}

### profile
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RWb3pGdXRBY2Nlc3NUb2tlbiIsImp0aSI6Ijk1OTk3YTdjLTI0YmItNDU1Yi04YWJkLTJkOTc4N2VmYjhlYyIsImlhdCI6MTY5MjAwNzcyOCwiVXNlcklkIjoiMSIsIk5hbWUiOiJBbkxlIiwiRW1haWwiOiJhbi5sZXRoYW5oM0BnbWFpbC5jb20iLCJVc2VybmFtZSI6ImFubGUiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2OTIwMDc3MjgsImV4cCI6MTY5MjAxMTMyOCwiaXNzIjoiSldUVm96RnV0V2ViQXBpIiwiYXVkIjoiSldUVm96RnV0V2Vic2l0ZSJ9.uYpqalMocOBuHMF_HMm3DHc7SQkM8dd1Pcwmnm3dKP4
GET https://vozfc.io.vn/test/user/profile
Authorization: Bearer {{token}}

### match 
GET https://vozfc.io.vn/test/match
Authorization: Bearer {{token}}

